class AppConstants {
  AppConstants._();

  static const String appName = 'MAttendance';
  static const String appVersion = '1.0.0';

  // API
  static const String apiBaseUrl = 'https://api.mattendance.com'; // Production URL
  static const String apiDevUrl = 'http://10.0.2.2:5001'; // Android emulator → localhost

  // Google OAuth — must match GoogleAuth:ClientId in API appsettings.json
  // OLD ID Generated by Arshad static const String googleClientId = '1053038395822-k2j0kru3v9uifr8m0ace4cj5up5lfcfs.apps.googleusercontent.com';
  // OLD using (doesn't work) static const String googleClientId = '949826765788-7trmkj3jniv9q2kcdlrd7bc8sibhpudd.apps.googleusercontent.com';
  static const String googleClientId =
      '615219020722-328p6rose15gud0s594nao396rhioh9a.apps.googleusercontent.com';

  // Hive box names
  static const String offlinePunchBox = 'offline_punches';
  static const String cacheBox = 'cache';
  static const String geofenceSettingsBox = 'geofence_settings';
  static const String shiftsBox = 'shifts';
  static const String tokenBackupBox = 'token_backup';

  // Timeouts
  static const Duration connectTimeout = Duration(seconds: 15);
  static const Duration receiveTimeout = Duration(seconds: 30);

  // Offline queue
  static const int maxRetryCount = 3;

  // Punch
  static const int qrTokenExpiryMinutes = 5;

  /// Auto punches (geofence/WiFi) queued offline expire after this window —
  /// an enter event + long outage is stale; punching hours later is wrong.
  static const Duration autoPunchQueueTtl = Duration(minutes: 15);
}
